version: "2"

services:
  api:
    build:
      dockerfile: api.Dockerfile
      context: .
    ports: 
      - 8080:8080
    depends_on:
        - redis
    environment:
        - REDIS_HOST=redis:6379
  
  worker:
    build:
      dockerfile: worker.Dockerfile
      context: .
    depends_on:
        - redis
    environment:
        - REDIS_HOST=redis:6379
  
  redis:
    image: redis
    ports: 
      - 6379:6379
  
  redis-commander:
    image: rediscommander/redis-commander 
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on: 
      - redis
    ports:
      - 8081:8081