version: "3.0"

services:
  webservice:
    build:
      context: .
    image: 09webservice
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mongo

  mongo:
    image: mongo:4.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017